[package]
name = "bartib"
version = "0.1.0"
authors = ["Nikolas Schmidt-Voigt <nikolas.schmidt-voigt@posteo.de>"]
description = "A simple timetracker for the command line"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
chrono = "0.4"
clap = "~2.33"
thiserror = "1.0"
anyhow = "1.0.42"
termion = "*"